/**
 * Created by cloud.wong on 2017/6/26.
 */
export const RECORD_USERINFO = 'RECORD_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PORDUCT = 'UPDATE_PRODUCT'

export const RECORD_ADDRESS = 'RECORD_ADDRESS'
export const ADD_ADDRESS = 'ADD_ADDRESS'
export const CHOOSE_ADDRESS = 'CHOOSE_ADDRESS'
export const CONFIRM_ADDRESS = 'CONFIRM_ADDRESS'
export const SAVED_ADDRESS = 'SAVED_ADDRESS'
export const RECORD_ADDRESSID = 'RECORD_ADDRESSID'

export const CONFIRM_INVOICE = 'CONFIRM_INVOICE'
export const ADD_INVOICE = 'ADD_INVOICE'

export const RECORD_ORDERID = 'RECORD_ORDERID'
